travis: improve OS X run times

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -44,9 +44,13 @@ install:
     if [[ $TRAVIS_OS_NAME == "osx" ]]
     then
       brew update || brew update # try again if it fails
-      brew upgrade
-      brew reinstall openssl
-      brew reinstall pyenv
+      for package in openssl pyenv; do
+        if ! brew outdated $package; then # exit status is inverted from what you'd expect
+          brew upgrade $package
+        else
+          brew reinstall $package # for good measure
+        fi
+      done
       eval "$(pyenv init -)"
       env PYTHON_CONFIGURE_OPTS="--enable-framework" pyenv install --skip-existing 3.5.2
       pyenv global 3.5.2
